### ISSUE TITLE
Bug fix and update for new version of sysbench

### ISSUE THREAD

**Issue by prl77** [tsuna/sysbench-tools#1]
1) I found a bug where the writes/sec metric was not properly stored due to misspelling of var name on line 145 and would therefore not show any results. 
2) New version of sysbench (v0.5) has slightly changed the output, so I updated the script to use the new strings on line 121 and 150.

Thanks a million for this script, tsuna!  Amazing work and saved me tons of time and frustration.

-Peter

DIFF:

```
121c121
<                 "\s*(\d+) Read, (\d+) Write, (\d+)"

---
>                 "\s*(\d+) reads, (\d+) writes, (\d+)"
145c145
<       record("nwrite", nwrite / total_time)

---
>       record("nwriteps", nwrite / total_time)
150c150
<     elif line == "    per-request statistics:\n":

---
>     elif line == "    response time:\n":
```

**Comment by tsuna** [comment]
Hi Peter,
thanks for your report.  Can you please confirm that the script now works as expected with the change above?  I also committed tsuna/sysbench-tools@f8dd4144b732c3c0cd2859bd3f2e77a35875106c to fix the typo in the variable name, thanks for pointing that out.
